INSERT INTO AUTOR VALUES('1','JUAN PEREZ','JUANP@GMAIL.COM','M');
INSERT INTO AUTOR VALUES('2','PEDRO LOPEZ','PEDROL@YAHOO.COM','M');
INSERT INTO AUTOR VALUES('3','LUISA MARTINEZ','LUISAM@GMAIL.COM','F');
INSERT INTO AUTOR VALUES('4','MARIA MEDINA','MARIAM@HOTMAIL.COM','F');
INSERT INTO AUTOR VALUES('5','AMBAR JACKSON','AMBARJACK@GMAIL.COM','F');