INSERT INTO AUTOR_NACIONALIDAD VALUES('1','1');
INSERT INTO AUTOR_NACIONALIDAD VALUES('2','2');
INSERT INTO AUTOR_NACIONALIDAD VALUES('3','3');
INSERT INTO AUTOR_NACIONALIDAD VALUES('4','4');
INSERT INTO AUTOR_NACIONALIDAD VALUES('5','5');
