INSERT INTO LIBRO_PRESTAMO VALUES('1','1');
INSERT INTO LIBRO_PRESTAMO VALUES('3','1');
INSERT INTO LIBRO_PRESTAMO VALUES('5','2');
INSERT INTO LIBRO_PRESTAMO VALUES('8','2');
INSERT INTO LIBRO_PRESTAMO VALUES('2','3');
INSERT INTO LIBRO_PRESTAMO VALUES('4','3');
INSERT INTO LIBRO_PRESTAMO VALUES('7','4');