INSERT INTO NACIONALIDAD VALUES('1','ESTADOS UNIDOS');
INSERT INTO NACIONALIDAD VALUES('2','COLOMBIA');
INSERT INTO NACIONALIDAD VALUES('3','ESPAÑA');
INSERT INTO NACIONALIDAD VALUES('4','CHINA');
INSERT INTO NACIONALIDAD VALUES('5','ALEMAN');
