INSERT INTO TEMA VALUES('1','MATEMATICAS');
INSERT INTO TEMA VALUES('2','ESPAÑOL');
INSERT INTO TEMA VALUES('3','INFORMATICA');
INSERT INTO TEMA VALUES('4','BIOLOGIA');
INSERT INTO TEMA VALUES('5','ANATOMIA');