INSERT INTO USUARIO_CARRERA VALUES('1','1');
INSERT INTO USUARIO_CARRERA VALUES('2','2');
INSERT INTO USUARIO_CARRERA VALUES('3','3');
INSERT INTO USUARIO_CARRERA VALUES('4','1');
INSERT INTO USUARIO_CARRERA VALUES('5','2');