/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spinner_swing;

import javax.swing.JOptionPane;

/**
 *
 * @author Cong. Carora
 */
public class Proyeccion_diplomado extends javax.swing.JFrame {

    /**
     * Creates new form Proyeccion_diplomado
     */
    public Proyeccion_diplomado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIngresos = new javax.swing.JPanel();
        lblIngresos = new javax.swing.JLabel();
        lblValorDiplomado = new javax.swing.JLabel();
        txtVarloDiplomado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblCostos = new javax.swing.JLabel();
        lblDocenciaGrupo = new javax.swing.JLabel();
        lblPlataformaGrupo = new javax.swing.JLabel();
        lblAdmon = new javax.swing.JLabel();
        txtDocenciaGrupo = new javax.swing.JTextField();
        txtPlataformaGrupo = new javax.swing.JTextField();
        txtAdmon = new javax.swing.JTextField();
        btnProyeccion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        spigrupos = new javax.swing.JSpinner();
        lblGrupos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyeccion Ingresos-Costos Diplomado");

        pnlIngresos.setBackground(new java.awt.Color(255, 255, 102));

        lblIngresos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIngresos.setForeground(new java.awt.Color(255, 0, 0));
        lblIngresos.setText("Ingresos");

        lblValorDiplomado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValorDiplomado.setText("Valor diplomado por persona:");

        javax.swing.GroupLayout pnlIngresosLayout = new javax.swing.GroupLayout(pnlIngresos);
        pnlIngresos.setLayout(pnlIngresosLayout);
        pnlIngresosLayout.setHorizontalGroup(
            pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosLayout.createSequentialGroup()
                .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblIngresos))
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblValorDiplomado)
                        .addGap(18, 18, 18)
                        .addComponent(txtVarloDiplomado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlIngresosLayout.setVerticalGroup(
            pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosLayout.createSequentialGroup()
                .addComponent(lblIngresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorDiplomado)
                    .addComponent(txtVarloDiplomado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        lblCostos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCostos.setForeground(new java.awt.Color(255, 0, 0));
        lblCostos.setText("Costos");

        lblDocenciaGrupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDocenciaGrupo.setText("Docencia por grupo: ");

        lblPlataformaGrupo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPlataformaGrupo.setText("Plataforma por grupo: ");

        lblAdmon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAdmon.setText("Administrativos: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdmon)
                            .addComponent(lblPlataformaGrupo)
                            .addComponent(lblDocenciaGrupo))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPlataformaGrupo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(txtDocenciaGrupo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdmon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblCostos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCostos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocenciaGrupo)
                    .addComponent(txtDocenciaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlataformaGrupo)
                    .addComponent(txtPlataformaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmon)
                    .addComponent(txtAdmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnProyeccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnProyeccion.setForeground(new java.awt.Color(255, 0, 0));
        btnProyeccion.setText("Proyeccion Ingresos-Costos");
        btnProyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyeccionActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        spigrupos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lblGrupos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGrupos.setText("Cantidad de grupos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spigrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spigrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGrupos))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnProyeccion)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnProyeccion)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyeccionActionPerformed
        int grupos;
        double valor_diplomado, docencia, plataforma, admon, ingresos, gastos;
        String mensaje;
        Diplomado obj_diplomado;
        valor_diplomado=Double.parseDouble(txtVarloDiplomado.getText());
        docencia=Double.parseDouble(txtDocenciaGrupo.getText());
        plataforma=Double.parseDouble(txtPlataformaGrupo.getText());
        admon=Double.parseDouble(txtAdmon.getText());
        grupos=(int)spigrupos.getValue();
        obj_diplomado=new Diplomado();
        obj_diplomado.setValor_diplomado(valor_diplomado);
        obj_diplomado.setDocencia(docencia);
        obj_diplomado.setPlataforma(plataforma);
        obj_diplomado.setAdmon(admon);
        obj_diplomado.setGrupos(grupos);
        ingresos=obj_diplomado.calcular_ingresos();
        gastos=obj_diplomado.calcular_costos();
        mensaje="Ingresos: "+ingresos+" Gastos: "+gastos;
        JOptionPane.showMessageDialog(null, mensaje);
    }//GEN-LAST:event_btnProyeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyeccion_diplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyeccion_diplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyeccion_diplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyeccion_diplomado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyeccion_diplomado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProyeccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdmon;
    private javax.swing.JLabel lblCostos;
    private javax.swing.JLabel lblDocenciaGrupo;
    private javax.swing.JLabel lblGrupos;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblPlataformaGrupo;
    private javax.swing.JLabel lblValorDiplomado;
    private javax.swing.JPanel pnlIngresos;
    private javax.swing.JSpinner spigrupos;
    private javax.swing.JTextField txtAdmon;
    private javax.swing.JTextField txtDocenciaGrupo;
    private javax.swing.JTextField txtPlataformaGrupo;
    private javax.swing.JTextField txtVarloDiplomado;
    // End of variables declaration//GEN-END:variables
}
